### ISSUE TITLE
Lib purpose and documentation?

### ISSUE THREAD

**Issue by markerikson** [talibasya/redux-store-ancillary#1]
Hi.  Skimming through the code, it looks like you've got _something_ useful here, but I can't tell exactly what all the uses are.  Any chance you could add some documentation or examples?

Also, I see a couple small code issues.  First, your popup reducer is generating random IDs.  That should be done on the action creator side so that the reducers are pure functions.  Second, your `deepCopy` util methods aren't actually deep copying, they're doing one or two levels of shallow copying.  That may actually be what you want, but it doesn't match the name.  (Also, in the popup reducer version of `deepCopy`, the `slice()` call is unneeded because `map()` returns a new array.)

**Comment by talibasya** [comment]
@markerikson  Hi. Thanks for your attention. I'm glad to see you find _something_ useful here 😺 
The basic idea is prepare **universal** library, which accelerates implementing your projects (as React and React-native/React VR etc) + redux + redux-thunk. (with ready routine things like popups, notifications, async actions, spinners logic. **just logic**). Basically was planed to help with projects at work, but then I decided: here are no commercial ideas/sources then why not to share ? 😄  

About your observation:
1. I didn't finish my first own scope what I wanted to do. I hope I will close that tomorrow (prepare notification provider, test on several starters).
Then prepare docs, examples for my guests.

2. The generating random IDs was my bad idea and experience for now (some react's issues). I don't use IDs for `popup`. Probably you mean `notification` ?

3. `deepCopy` - you wrote correctly. It's a not a really `deepCopy` (as it works on `lodash` for example). And yes. It was expected, cause for my "`deepCopy`" I don't want to include additional libraries like `lodash`, `underscore` (here is useful light things - just simply prepare routine logic). And actually here is no need a really `deepCopy`, cause no change deep objects in reducer. Only an array 😊 (I should rename the method)

4. With `slice` - you are right. Here is unneeded. I should remove that.

If you need describe how to use, I can share you currently used starter kit with examples. (Its a not ready for publish as a docs/examples)

Hope it helps you 😊
